create table if not exists public.marine_station_data (
  id bigint generated by default as identity primary key,
  station_id text not null,
  timestamp timestamptz not null,
  water_temperature double precision,
  current_u double precision,
  current_v double precision,
  current_speed double precision,
  current_direction double precision,
  salinity double precision,
  wave_height double precision,
  wave_direction double precision,
  wave_period double precision,
  source text not null default 'Copernicus Marine',
  raw_payload_json jsonb,
  created_at timestamptz not null default now(),
  constraint marine_station_data_station_time_unique unique (station_id, timestamp)
);

create index if not exists idx_marine_station_data_station_timestamp_desc
  on public.marine_station_data (station_id, timestamp desc);

alter table public.marine_station_data enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'marine_station_data'
      and policyname = 'marine_station_data_select_public'
  ) then
    create policy marine_station_data_select_public
      on public.marine_station_data
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'marine_station_data'
      and policyname = 'marine_station_data_service_role_all'
  ) then
    create policy marine_station_data_service_role_all
      on public.marine_station_data
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
